### ISSUE TITLE
Verify version compatibility with Kubernetes

### ISSUE THREAD

**Issue by andrewsykim** [digitalocean/digitalocean-cloud-controller-manager#101]
The latest version of DO CCM should support the latest stable Kubernetes and 2 major version before it. At the moment we only advertise that the latest version of CCM supports the latest stable version of Kubernetes because those are the only versions we tested. We should verify that DO CCM is compatible with the latest stable and 2 major versions behind.

**Comment by timoreimann** [comment]
I wondered if I could take a stab on this one.

Presumably, we want to have some kind of automated test? What I am thinking of is to fire up a set of droplets, install Kubernetes (through kubeadm, another tool, or some helper scripts such as https://github.com/caglar10ur/dok8s) with DO's CCM, and finally run some end-to-end tests through it.

Happy to hear your thoughts on my proposal or any other approach.

**Comment by andrewsykim** [comment]
@timoreimann go for it! I had written a simliar thing before to run E2E tests for kube-router https://github.com/cloudnativelabs/kube-router/pull/382 in case it helps.

**Comment by timoreimann** [comment]
@andrewsykim great, I'll see if I can put something together. That kube-router PR looks pretty helpful, thanks for head start!

**Comment by timoreimann** [comment]
Quick update: Been working on this one, will hopefully be able to submit a WIP PR soon. Stay tuned. :)
