### ISSUE TITLE
Node labels and addresses - Not working

### ISSUE THREAD

**Issue by sandeepone** [digitalocean/digitalocean-cloud-controller-manager#106]
After deploying the DigitalOcean CCM, I can create and access loadbalancers for the service type:loadbalancer.

But I can't get the node labels "instance type" and "region". 
"External IP" in address not set in the node.

DigitalOcean CCM   -  0.1.6
Kubernetes version  - v1.10.4
Container Linux by CoreOS 1745.7.0 (Rhyolite)   4.14.48-coreos-r2

Cluster Creation with terraform - kubeadm - DO CCM
https://github.com/kubernetes-digitalocean-terraform/kubernetes-digitalocean-terraform

Thanks in advance

**Comment by andrewsykim** [comment]
Hi @sandeepone, thanks for opening this issue! 

Can you show the logs from DigitalOcean CCM?

**Comment by sandeepone** [comment]
Apologies in delay. Here the log

https://pastebin.com/raw/Jp8mhGr3

```
E0617 11:11:52.398756       1 node_controller.go:158] InstanceExistsByProviderID: Error fetching by providerID: providerID cannot be empty string Error fetching by NodeName: GET https://api.digitalocean.com/v2/droplets?per_page=100: 502
```

**Comment by andrewsykim** [comment]
Can you show output of 
```
kubectl get node
```
and 
```
doctl compute droplet list
```
?

**Comment by andrewsykim** [comment]
It seems like your node can't be found cause the digitalocean API is returning a 502 there.

**Comment by sandeepone** [comment]
```
kubectl get node

NAME            STATUS    ROLES     AGE       VERSION
k8s-master      Ready     master    7d        v1.10.4
k8s-worker-01   Ready     <none>    7d        v1.10.4
k8s-worker-02   Ready     <none>    7d        v1.10.4
```

```
doctl compute droplet list
ID          Name             Public IPv4        Private IPv4     Public IPv6    Memory    VCPUs    Disk    Region    Image                       Status    Tags          Features              Volumes
97755219    k8s-master       XXX.XXX.XXX.XXX    10.130.81.83                    2048      2        60      sgp1      CoreOS 1745.6.0 (stable)    active    k8s-master    private_networking    
97755541    k8s-worker-02    XXX.XX.XX.XXX      10.130.66.100                   4096      2        80      sgp1      CoreOS 1745.6.0 (stable)    active    k8s-worker    private_networking    
97755542    k8s-worker-01    XXX.XXX.XX.XXX     10.130.67.7                     4096      2        80      sgp1      CoreOS 1745.6.0 (stable)    active    k8s-worker    private_networking    
```

When I added traefik with ```type: LoadBalancer``` DO created the LoadBalancer and added the IP's and ports correctly in DO LoadBalancer. But I see those 502 errors in logs

**Comment by sandeepone** [comment]
I notice 524 error instead of 502

```
E0621 10:01:00.614079       1 node_controller.go:166] NodeAddress: Error fetching by providerID: providerID cannot be empty string Error fetching by NodeName: GET https://api.digitalocean.com/v2/droplets?per_page=100: 524
```

**Comment by sandeepone** [comment]
@andrewsykim no sorries. I'll try to spin up a new cluster and update you by end of the day.

**Comment by sandeepone** [comment]
Same error. I'm giving up for now. 

Thanks @andrewsykim for your help. As we're busy now to deploy our service and its not major issue right now.

I'll further investigate on k8 1.11 after a week.

**Comment by andrewsykim** [comment]
Closing this for now, feel free to re-open when you revisit this
