### ISSUE TITLE
Cyclic dependency on network and ccm

### ISSUE THREAD

**Issue by EnigmaCurry** [digitalocean/digitalocean-cloud-controller-manager#129]
Hi, I'm trying to setup a digitalocean-ccm based cluster with kubespray. With cloud-provider set to 'external', I'm unable to start any pods until ccm is ready (makes sense). However, I cannot start ccm until my network is up and running. So it's a deadlock.

* If I start flannel first, flannel never starts, due to the taint of cloud-provider=external
* If I start ccm first, it never starts, due to nodes in NotReady state (because network is not ready.)

I've applied the following config:

 * kubelet --cloud-provider=external
 * hostnames == droplet names, and no override-hostname used on kubelet.

Now kubespray has this notion of 'cloud' networking, which I have also tried (instead of 'flannel'). In this case, ccm does indeed startup, and my nodes get initialized successfully! But, I do not get a cluster subnet (10.233.0.0) setup. I assume this is just not implemented in DO-ccm to assign IPs like flannel does? I cannot install helm to such a cluster, it just times out trying to reach a 10.233.0.1 ip address.

Can you provide any details about tested cluster networking configs? I've tried 'cloud', 'flannel', and 'calico', but to no avail. Do you think I need to add a tolerance for flannel to start even in uninitialized state?

**Comment by andrewsykim** [comment]
Hi! This is usually why we set `hostNetwork: true` and some tolerations to the CCM to avoid the cyclical dependencies (see recommended daemonset: https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/releases/v0.1.7.yml#L20-L32). Have you tried using those?

**Comment by EnigmaCurry** [comment]
Fantastic! Adding similar tolerations to my flannel DaemonSet made it go. Thanks again.
