### ISSUE TITLE
Set droplet tags as kubernetes labels

### ISSUE THREAD

**Issue by gianarb** [digitalocean/digitalocean-cloud-controller-manager#135]
I think it can be very useful to set up the cloud-controller-manager to set the tags attached to the droplet as labels for the node.

This feature will give me the automation I need to make a more complex cluster topology

**Comment by andrewsykim** [comment]
Starting work on this

**Comment by timoreimann** [comment]
I am closing this one in favor of #136 which has accumulated more context by now. Please see [my comment here](https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/136#issuecomment-466504830) outlining the next steps forward.
