### ISSUE TITLE
HTTPS redirect not working

### ISSUE THREAD

**Issue by akoutmos** [digitalocean/digitalocean-cloud-controller-manager#143]
I tried creating a LoadBalancer based off the example here: https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/http-nginx-with-redirect.yml

It seems as though having `service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"` has no impact on the created LoadBalancer. When I go to my DO admin portal the SSL setting is set to "No redirect". If I edit that setting in the portal, then redirect works as expected. Seems like it is a problem with how the LoadBalancer is provisioned.

**Comment by andrewsykim** [comment]
@akoutmos is this on the managed offering?

**Comment by akoutmos** [comment]
Yes that is correct.

**Comment by andrewsykim** [comment]
@akoutmos best thing here might be to open a support ticket instead.

**Comment by andykent** [comment]
Just to confirm, I hit this today too. I am also on the managed service. 

It seems like maybe the version running on the managed service might be trailing behind this repo? Although maybe not as I couldn't figure out a way to check what version is actually running, the deployment doesn't seem to be listed in the `kube-system` namespace as recommended in the docs here so I guess there is something different going on.

Maybe related but maybe not, I was also unable to add a certificate to the LB, using `service.beta.kubernetes.io/do-loadbalancer-certificate-id` and `service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"` resulted in a PUT api error from DO sating that either the certificate or pass through option must be set so it seems like the cert id isn't making it as far as the API call from what I could tell.

I will open a support ticket also.

**Comment by joonas** [comment]
@andykent @akoutmos would you be able to open up a ticket with our support team so that they can point it out for our team to take a look, we should be able to get you squared away pretty quickly once we can identify the clusters in question.

Thanks!

**Comment by andykent** [comment]
Thanks @joonas I can confirm that support updated the master and it resolved the issue so I think you can close this as fixed.

**Comment by fatih** [comment]
Thank you @andykent for the feedback and glad to see it's fixed for you. Please feel free to open an issue again if you see any problems or have questions.
