### ISSUE TITLE
Allow setting different protocol for health checks

### ISSUE THREAD

**Issue by daimoniac** [digitalocean/digitalocean-cloud-controller-manager#145]
We need to be able to set a different protocol for health checks than for the balanced service.

http is being balanced (with ssl termination), but the health check should be a simple tcp one.
but the protocol seems to be hardcoded to the balanced service ones here:
https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/1938ec185300d91f49ed305ecdc65c83acb356c2/cloud-controller-manager/do/loadbalancers.go#L361

![image](https://user-images.githubusercontent.com/7752824/48835337-2c527b80-ed80-11e8-97dc-416aea3264c8.png)

**Comment by andrewsykim** [comment]
Hi @daimoniac! We can add a new service annotation to specify health check protocol. Would that work?

**Comment by daimoniac** [comment]
Perfect!

Am Mi., 21. Nov. 2018, 17:58 hat Andrew Sy Kim <notifications@github.com>
geschrieben:
