### ISSUE TITLE
How to forward HTTPS to HTTPS with TLS-termination

### ISSUE THREAD

**Issue by Ratedev** [digitalocean/digitalocean-cloud-controller-manager#146]
Is there a way to create a forwarding rule that redirects HTTPS to HTTPS and does TLS termination with a supplied certificate like it is in the DigitalOcean web ui?

**Comment by andrewsykim** [comment]
Hi! HTTPS -> HTTPS? Did you mean HTTPS -> HTTP?

**Comment by Ratedev** [comment]
> Hi! HTTPS -> HTTPS? Did you mean HTTPS -> HTTP?

I mean HTTPS to HTTPS. I want the traffic between LoadBalancer and my pods to be encrypted. 

But the main reason is that when i access a URL that points to the LoadBalancer from within the cluster, the request does not reach the LoadBalancer but is handled inside my kubernetes cluster bacause the LoadBalancer IP is handled inside the kluster by kubernetes logic. 
That's why my endpoint inside the cluster needs to handle HTTPS, so the LoadBalancer should forward HTTPS to HTTPS. I Also need the original source IP, so theLoadBalancer needs to perform TLS termination.

I can configure it in the web ui but did'nt find a way to set the same settings by a k8s LoadBalancer service and do-cloud-controller-manager:
![lb_example](https://user-images.githubusercontent.com/6561296/48892659-dbee2300-ee3e-11e8-894b-571d82ef37e4.png)


I hope it's a little bit more clear now, what i need.

**Comment by andrewsykim** [comment]
Thanks for clarifying!

> the LoadBalancer should forward HTTPS to HTTPS

This by definition means that there will be no TLS termination. If you want to forward HTTPS traffic you need to set the TLS port annotation (`service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"`) and TLS pass through (`service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"`).

**Comment by andrewsykim** [comment]
Here's an example: https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/https-with-pass-through-nginx.yml

**Comment by andrewsykim** [comment]
Closing this for now, let me know if this is still a problem

**Comment by jcassee** [comment]
This could be a work-around for #193. Using passthrough does not add X-Forward-* / Forwarded headers, hiding the client IP address.
