### ISSUE TITLE
Better state handling of LBs

### ISSUE THREAD

**Issue by andrewsykim** [digitalocean/digitalocean-cloud-controller-manager#153]
We should add smarter logic for ensuring load balancers. Right now we check for the "active" state when we initially create the LB, but on follow up reconciliation of LBs, we only check for existence. This makes it difficult to handle cases where an LB may be created properly but is in a bad state.

**Comment by timoreimann** [comment]
Closing this one as I think we haven't run into a case of LBs going into an error state for a reasonable time period.
