### ISSUE TITLE
Creating service of type loadbalancer doesn't provision loadbalancer or public ip when using terraform-helm

### ISSUE THREAD

**Issue by maxwedwards** [digitalocean/digitalocean-cloud-controller-manager#162]
To reproduce this issue, install stable/nginx-ingress chart using terraform helm provider. The ingress controller doesn't end up with a loadbalancer or public ip, instead the service just shows <pending> for public ip.

If you install the chart using helm directly without terraform helm provider the public ip gets assigned and the service-controller raises a couple of events: EnsuringLoadBalancer and EnsuredLoadBalancer.

I'm not sure this is a problem with DO's CCM and could be a weird setting on the terraform-helm provider but something is preventing the service-controller from creating the required resources and raising the events.

**Comment by timoreimann** [comment]
My first impression is that if installing the Helm chart directly works but not so when run through the Terraform Helm provider, it looks more like an issue with the Terraform Helm provider.

I tried to reproduce this real quick yesterday but ran into a few issues with Helm (most likely because this is me using it for the first time). I'll try again once time permits; any more detailed reproduction steps from yours might help to speed things up though.

You may also want to consider filing a bug report in the Terraform Helm provider repo just in case the issue lies with them.

**Comment by timoreimann** [comment]
@maxwedwards I had some issues running the Terraform plan to success in the given region. However, once I switched to SFO2, things started to work. Here's the overview of all services running:

```
$ kubectl --kubeconfig org-kube-cluster-kubeconfig.yaml get svc
NAME                                     TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
kubernetes                               ClusterIP      10.245.0.1      <none>           443/TCP                      8m
my-nginx-nginx-ingress-controller        LoadBalancer   10.245.8.77     157.230.75.5     80:31369/TCP,443:30622/TCP   7m
my-nginx-nginx-ingress-default-backend   ClusterIP      10.245.132.94   <none>           80/TCP                       7m
nginx-ingress-controller                 LoadBalancer   10.245.15.25    157.230.75.194   80:31916/TCP,443:31200/TCP   7m
nginx-ingress-default-backend            ClusterIP      10.245.202.48   <none>           80/TCP                       7m
```

It shows that external IPs have been assigned. I also see two LBs in my DO dashboard showing up as healthy. Do you want to give SFO2 a try just to see if I haven't been just lucky?

**Comment by maxwedwards** [comment]
Rather suspiciously all has started working in London region. I have not changed anything but IP addresses are now being assigned. Must have been your scrutiny @timoreimann so thanks ever so for taking the time.
