### ISSUE TITLE
UDP ingress into cluster

### ISSUE THREAD

**Issue by naphta** [digitalocean/digitalocean-cloud-controller-manager#164]
Trying to expose some ports of TCP and UDP externally, TCP was a piece of cake using an ingress controller and the DO loadbalancer but I'm unsure on how to proceed with UDP.

How we run our clusters on prem at the moment we're using metallb in layer2 mode but I'm sure that wouldn't get me very far on DO!

Any advice?

**Comment by nanzhong** [comment]
At the moment our DO load balancers are not able support UDP.

**Comment by naphta** [comment]
@nanzhong I'm wondering if there's a sensible workaround for the time being?

**Comment by timoreimann** [comment]
@naphta I suppose you could expose your UDP server(s) on a NodePort and direct traffic towards that. It'll make your setup more complicated as you need to manage request distribution across the nodes yourself, however, especially when taking node replacements and failures into account.

**Comment by timoreimann** [comment]
I'll be closing the issue for now. @naphta feel free to file a support ticket requesting the feature you are asking for.
