### ISSUE TITLE
Loadbalancer -- Firewall Support / Forward IP Headers?

### ISSUE THREAD

**Issue by ptariche** [digitalocean/digitalocean-cloud-controller-manager#179]
I recently noticed there is a lack of firewall support for the load balancer and due to the way traffic is routed: it limits control and security someone may have at ingress.

For example: 

If I were to setup a droplet and place firewall rules, limiting traffic only from Cloudflare IP's, this is possible.

This same example is not possible via firewall rules today for loadbalancers  because of the type of DO loadbalancer in its OSI layer; the same cannot also be done at the application layer of the ingress controller due to a lack of headers because of this.

**Comment by ptariche** [comment]
Related to #144

**Comment by timoreimann** [comment]
@ptariche I think what you're basically asking for is support for [`loadBalancerSourceRanges`](https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service). AFAICS, this would require extending the Load Balancers product first to allow for fine-grained IP access control.

#144 and the Community links available there suggest some workarounds. I know it's not ideal though, so I'm happy to forward your feedback accordingly.

**Comment by ptariche** [comment]
💯

**Comment by ptariche** [comment]
https://blog.digitalocean.com/load-balancers-now-support-proxy-protocol/?utm_source=local&utm_medium=Email&utm_campaign=LBProxyProtocolRelease

👏 👏
