### ISSUE TITLE
Implement GetZoneByProviderID and GetZoneByNodeName

### ISSUE THREAD

**Issue by andrewsykim** [digitalocean/digitalocean-cloud-controller-manager#18]
As per https://github.com/kubernetes/kubernetes/issues/50926, DO CCM should implement those methods so we accurately represent the region of droplets instead of assuming droplets are in the same region as CCM.

**Comment by klausenbusk** [comment]
Did this fix the mentioned issue in https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/24#issuecomment-331928046 ?
The code still seems to contain the "broken" logic?

**Comment by andrewsykim** [comment]
@klausenbusk this should have been fixed. What code are you referring to? `GetZone()`?

**Comment by klausenbusk** [comment]
> @klausenbusk this should have been fixed. What code are you referring to? GetZone()?

This code: https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/9fbae98ea3574bdf5e7afaa29a3faa75b3a8caef/do/metadata.go#L28-L30 which is used here: https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/f029698c18dc003ff643d2b03e00a39cba1eee1e/do/cloud.go#L68 and then passed as arguments here: https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/f029698c18dc003ff643d2b03e00a39cba1eee1e/do/cloud.go#L75-L77

Maybe I just don't understand the code :)

**Comment by andrewsykim** [comment]
Our implementation for GetZoneByProviderID and GetZoneByName https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/do/zones.go#L43-L70
