### ISSUE TITLE
Security flaw token exposed

### ISSUE THREAD

**Issue by giovannicandido** [digitalocean/digitalocean-cloud-controller-manager#211]
The bearer token is exposed to end users of kubernetes clusters when api call fail.

Steps to reproduce:

Create a secret with a invalid content lets say just "\n" at the end (quite common operating base64)

Provision a pvc

Check the pvc description:

`kubectl describe pvc pv1`

> Status:        Pending
> Volume:
> Labels:        <none>
> Annotations:   control-plane.alpha.kubernetes.io/leader:
>                  {"holderIdentity":"b766b5f3-635e-11e9-8310-0addbdcc6f90","leaseDurationSeconds":15,"acquireTime":"2019-04-20T11:24:42Z","renewTime":"2019-...
>                kubectl.kubernetes.io/last-applied-configuration:
>                  {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pv1","namespace":"default"},"spec":{"accessModes":[...
>                volume.beta.kubernetes.io/storage-provisioner: external/digitalocean
> Finalizers:    [kubernetes.io/pvc-protection]
> Capacity:
> Access Modes:
> VolumeMode:    Filesystem
> Events:
>   Type       Reason                Age                 From                                                                                                  Message
>   ----       ------                ----                ----                                                                                                  -------
>   Normal     Provisioning          43s (x12 over 68s)  external/digitalocean digitalocean-provisioner-675676d9d9-45nv8 b766b5f3-635e-11e9-8310-0addbdcc6f90  External provisioner is provisioning volume for claim "default/pv1"
>   Warning    ProvisioningFailed    41s (x13 over 68s)  external/digitalocean digitalocean-provisioner-675676d9d9-45nv8 b766b5f3-635e-11e9-8310-0addbdcc6f90  Failed to provision volume with StorageClass "do-nyc1": Post https://api.digitalocean.com/v2/volumes: net/http: invalid header field value "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n" for key Authorization
>   Normal     ExternalProvisioning  29s (x25 over 68s)  persistentvolume-controller                                                                           waiting for a volume to be created, either by external provisioner "external/digitalocean" or manually created by system administrator

Observe that the Warning message exposes the Bearer header token to any user provisioning a volume.

**Expected behavior:**  The contents of the token must never be logged, specially in contexts where non admin have access.

**Comment by timoreimann** [comment]
Thanks for reporting. I suppose this is best addressed in https://github.com/digitalocean/csi-digitalocean.

@fatih didn't we recently remove the token from the worker nodes? would that possibly solve the issue already?

**Comment by fatih** [comment]
Which version do you use @giovannicandido ?  It's true what we removed it from our `DO` Kubernetes offering. However the open source CSI plugin still uses the secret stored in `K8S`.

**Comment by timoreimann** [comment]
Closing this one as I believe any follow up discussions are best taken to our CSI repository, as explained above.
