### ISSUE TITLE
Renaming load balancers causes a new instance to be created leaving the previous one dangling

### ISSUE THREAD

**Issue by mishushakov** [digitalocean/digitalocean-cloud-controller-manager#224]
Hey,
I encountered issue, with my managed Digital Ocean Kubernetes. I have exposed my ingress controller with Service type LoadBalancer and it all worked fine, till the automatic upgrade was triggered.

I noticed, that during the upgrade new droplets are created and the yaml-definitions are recreated automatically. For the most part it worked very well, my services/deployments were running, but the cloud controller created new LoadBalancer with new IP-address. I noticed, that there is Kubernetes-native way to prevent it, by specifying `loadBalancerIP` in the yaml, but it didn't worked with DO. To fix this issue, I have changed the Service type to NodePort with reserved ports and created the LoadBalancer manually, so when DO triggers an upgrade, it won't create new LoadBalancer with new IP each time.

Hope you could help to solve this issue, since I spent a whole night fixing your "managed" service.

**Comment by timoreimann** [comment]
Sorry to hear you were having issues.

The recreate should clearly not happen: what CCM does is try to fetch the LB based on a predefined name (essentially the service object UUID) and only create one if it's found missing.

Did you possibly rename the DO LB manually? That would throw CCM off and indeed cause another LB to be created.

If you can rule that out, then I'd love to know your cluster UUID to look into the matter more thoroughly. You can send me the ID via email (see my Github profile) or via DM on the Kubernetes Slack channel.

Thanks.

**Comment by mishushakov** [comment]
Hey @timoreimann,
That's exactly what I thought caused the issue, since the LoadBalancer, that was being recreated always had the same name and IP. One thing I noticed too, is that there is no way to declare protocol in yaml (I want to use http/http2) and it's always tcp. 

Yes, as you said, i renamed my LB, just for convenience. After the upgrade It started to act really weird. When I renamed the automatically-provisioned LoadBalancer, a new one one was created right away and made me so crazy and angry...

I then, decided to create LB manually and expose the Service via NodePort, so don't have to fix things up after next upgrade and prevent LB recreation.

But there is no chance for me to know, that there is some internal dependency and I'm not allowed to rename LB with Managed Kubernetes.

I'd really like to help. Let me know, where I can find the UUID and I will send it right back to you.

Thank you 🐳

**Comment by timoreimann** [comment]
@mishushakov 

>But there is no chance for me to know, that there is some internal dependency and I'm not allowed to rename LB with Managed Kubernetes.

You're absolutely right on this one -- it's totally on me and my team to improve the situation here. I'll make sure we at least document this caveat prominently, and in parallel think of technical solutions to rule out the issue systematically.

>One thing I noticed too, is that there is no way to declare protocol in yaml (I want to use http/http2) and it's always tcp.

While [support for http2](https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/163) is yet to be done, you should already be able to specify HTTP through your Service manifest today. Please see our [service annotation documentation](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/4ece6cf89e7698402d958fdc9130907b12fcc81b/docs/controllers/services/annotations.md), and more specifically [`service.beta.kubernetes.io/do-loadbalancer-protocol`](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/4ece6cf89e7698402d958fdc9130907b12fcc81b/docs/controllers/services/annotations.md#servicebetakubernetesiodo-loadbalancer-protocol) that will allow you to pick one of http, https, or tcp. We also provide [a number of examples](https://github.com/digitalocean/digitalocean-cloud-controller-manager/tree/4ece6cf89e7698402d958fdc9130907b12fcc81b/docs/controllers/services/examples), one of them being [how to specify the HTTP protocol](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/4ece6cf89e7698402d958fdc9130907b12fcc81b/docs/controllers/services/examples/http-nginx.yml).

>Let me know, where I can find the UUID and I will send it right back to you.

There are (at least) two ways to get the UUID: You can either

- go the [Kubernetes page in your cloud control account](https://cloud.digitalocean.com/kubernetes/clusters), click on the cluster in question, and copy the UUID from the URL (it'll be structured like `https://cloud.digitalocean.com/kubernetes/clusters/<UUID>?i=<sequence of digits>`); or
- (if you have [`doctl`](https://github.com/digitalocean/doctl) installed) run `doctl kubernetes cluster list` and copy the _ID_ value from the cluster in question.

Thank you!

**Comment by mreithub** [comment]
Hi, I ran into the same issue with the last update (had more than one LB and renamed them to keep things 

My suggestion would be (one or a combination of):
- add another load balancer annotation, e.g. `service.beta.kubernetes.io/do-loadbalancer-name` to let the user decide on the name (and mention in the docs that that's what identifies it and must be unique for things to work as expected)
- use the kubernetes service name (which needs to be unique per k8s cluster) and find a way to not break existing installs (e.g. doing lookups for both the UUID and the service name in `GetLoadBalancerName()` and return the first one that actually exists)
  ... and maybe add a prefix like `k8s-` or the kubernetes cluster name

- at least update the documentation that LBs managed by k8s must not be renamed or they won't be found by the cluster manager

**Comment by nadinengland** [comment]
I've had the same issue too, again I renamed my load balancer for convenience.

I'm not super familiar with the CCM's internal, but I thought I might offer some input. Perhaps if DigialOcean allowed tags on LBs, just like Droplets, we'd be able to organise our services and still support the CCM's behaviour? Sorry if I'm missing something glaringly obvious that might already be preventing this.

**Comment by mishushakov** [comment]
I think DO should lock down the ability to rename LB, if it's created from k8s. They could use the

```yaml
metadata:
  name: name
```

in the Service yaml definition to name our LBs
Thanks.

**Comment by timoreimann** [comment]
Thanks for the brainstorming everybody, appreciated!

We actually [do tag LBs already](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/5a8136525c3a52b6cb84eb0e27967dc4aa2a6792/cloud-controller-manager/do/resources.go#L352) in CCM through DO's tag service. The issue with this approach right now is that LBs cannot be retrieved by tags. It's certainly something we could drive internally. Similar for the ability to lock down LB name changes.

What the LB does support though is lookup by LB UUID. So an idea I'm pondering about is to add an annotation to the Service object specifying the LB UUID and use that for direct lookups. The UUID should not be mutable, allowing users to rename LBs freely.
I need to give it some more thought and also try things out. The cloud provider framework that is calling into our implementation does some Service mutation on its own (to include the public/ingress IP address in the object once announced by the LB), so we need to be sure that conflicts are resolved adequately and in time.

The issue is definitely high on our priority list -- hopefully, we'll be able to get to it soon.

**Comment by timoreimann** [comment]
This just got fixed in master. The next CCM release (v0.1.17) is going to ship the fix.
