### ISSUE TITLE
No NodeIP - K8s fundamental broken

### ISSUE THREAD

**Issue by Berndinox** [digitalocean/digitalocean-cloud-controller-manager#237]
**Version**: 1.14.1
**Performed**: Recycled the initial nodepool and added some new pools
**Issue**:  All the new Nodes have not assigned an Internal and External IP. So there state is "NotReady"

`kubectl get nodes -o wide`
```
NAME           STATUS     ROLES    AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION         CONTAINER-RUNTIME
pool-02-oi7h   NotReady   <none>   92m   v1.14.1   <none>           <none>        Debian GNU/Linux 9 (stretch)   4.19.0-0.bpo.5-amd64   docker://18.9.2
pool-02-oi7k   NotReady   <none>   92m   v1.14.1   <none>           <none>        Debian GNU/Linux 9 (stretch)   4.19.0-0.bpo.5-amd64   docker://18.9.2
```

i tried to add "--node-ip=1.2.3.4" to "/etc/systemd/system/kubelet.service" and reloading the daemon, but that does not fix it.

i also tried:
`kubectl edit node host01`
and adding
```
metadata:
  annotations:
    alpha.kubernetes.io/provided-node-ip: 10.135.189.128
```
either does not solve the issue.

So i end up not beeing able to use my cluster cause my working, initial node pool is already removed.
Sadly the support is not reacting so far....

**Comment by timoreimann** [comment]
Hi @Berndinox, thanks for your report.

I understand this is a DIY cluster (that is, _not_ a DOKS one)? If so, could you share the complete log of the cloud-controller-manager pod?

It might also be interesting to know how you deployed your cluster.

Thank you!

**Comment by Berndinox** [comment]
Hy, this is a DO Managed Cluster! I just have Access to the Worker Nodes. BR Bernd

**Comment by timoreimann** [comment]
@Berndinox gotcha -- could you please send me your cluster UUID (it's in the URL on the cloud control panel) via email (see my Github profile) or via DM on the Kubernetes Slack? I can then look into the CCM logs.

(By the way, CCM also emits events in case of errors.)

Thanks!

**Comment by Berndinox** [comment]
@timoreimann thanks a lot for looking into it. mail is on the way

**Comment by Berndinox** [comment]
Thanks @timoreimann  - There was a missing access token - Solved
