### ISSUE TITLE
DO Proxy Protocol broken header 

### ISSUE THREAD

**Issue by peteychuk** [digitalocean/digitalocean-cloud-controller-manager#295]
Hi,

Related issue: https://github.com/kubernetes/ingress-nginx/issues/3996

Proxy protocol causes an error for within the cluster traffic:
`while reading PROXY protocol`

Any thoughts on this?

**Comment by timoreimann** [comment]
This is a known issue of kube-proxy. I have commented on the upstream issue at https://github.com/kubernetes/ingress-nginx/issues/3996#issuecomment-562027376.

Let's continue any further discussions on the Nginx controller issue or on the tracking issue I referenced in my comment.
