### ISSUE TITLE
Manifests for release v0.1.21 are missing

### ISSUE THREAD

**Issue by excieve** [digitalocean/digitalocean-cloud-controller-manager#296]
There's no `releases/v0.1.21.yml` file in either master or release tag.

**Comment by timoreimann** [comment]
@excieve shoot, not sure how we were able to miss that.

Thanks for pointing out. 👏  I've got a PR up to add the missing manifest.

**Comment by excieve** [comment]
Thanks for addressing it so quickly @timoreimann!
