### ISSUE TITLE
Service type LoadBalancer gets Master node Public IP as "External IP" instead LB IP

### ISSUE THREAD

**Issue by DavidZisky** [digitalocean/digitalocean-cloud-controller-manager#301]
After creating service type LoadBalancer, cloud-controller-manager creates properly LoadBalancer in DO and everything works but "External IP" is not being updated in service. It keeps being Pending. I checked the logs but I didn't find any issues. I'm testing on K8S 1.16 and latest cloud-controller release (v0.1.21)

**Comment by timoreimann** [comment]
Hi @DavidZisky 

What does `kubectl get event -n <namespace hosting the Service object>` give you?

**Comment by DavidZisky** [comment]
Hi @timoreimann 

Thanks for the quick reply :) I actually found one issue in events - so the forever pending state was simply due to ports being allocated already for the service. I chose different port and service got updated with ExternalIP BUT now there is another issue - it got updated with master node public  ip instead of LB IP. Events from that:

https://gist.github.com/DavidZisky/6a7a303be7fc078fa5ae8fa70c187dda

In cloud-controller-manager pod logs nothing interesting:

I1210 11:25:38.708742       1 event.go:255] Event(v1.ObjectReference{Kind:"Service", Namespace:"test1", Name:"nginxservice2", UID:"7fb95986-3728-41a6-aee0-aa3bed9c384d", APIVersion:"v1", ResourceVersion:"68841", FieldPath:""}): type: 'Normal' reason: 'EnsuringLoadBalancer' Ensuring load balancer
I1210 11:25:39.330680       1 event.go:255] Event(v1.ObjectReference{Kind:"Service", Namespace:"test1", Name:"nginxservice2", UID:"7fb95986-3728-41a6-aee0-aa3bed9c384d", APIVersion:"v1", ResourceVersion:"68841", FieldPath:""}): type: 'Normal' reason: 'EnsuredLoadBalancer' Ensured load balancer
I1210 11:27:43.425623       1 event.go:255] Event(v1.ObjectReference{Kind:"Service", Namespace:"test1", Name:"nginxservice2", UID:"7fb95986-3728-41a6-aee0-aa3bed9c384d", APIVersion:"v1", ResourceVersion:"69042", FieldPath:""}): type: 'Normal' reason: 'EnsuringLoadBalancer' Ensuring load balancer
I1210 11:27:44.139450       1 event.go:255] Event(v1.ObjectReference{Kind:"Service", Namespace:"test1", Name:"nginxservice2", UID:"7fb95986-3728-41a6-aee0-aa3bed9c384d", APIVersion:"v1", ResourceVersion:"69042", FieldPath:""}): type: 'Normal' reason: 'EnsuredLoadBalancer' Ensured load balancer

**Comment by timoreimann** [comment]
Could you share the output of `kubectl get service -o yaml <service>` and ideally also the load balancer UUID?

**Comment by DavidZisky** [comment]
> Could you share the output of `kubectl get service -o yaml <service>` and ideally also the load balancer UUID?

get service:

https://gist.github.com/DavidZisky/ae02634ca9ca6f34695fe3819c2cf462

The 165.xx IP is one of the workers public IP.

LB UUID: a7fb95986372841a6aee0aa3bed9c384 (if that's the one I see as "name" in LB list on DO?)

**Comment by timoreimann** [comment]
@DavidZisky very odd: the CCM implementation should only ever return the LB IP address for the ingress status field.

I wonder if this could be related to some API server behavior or switch. How did you build/install Kubernetes?

**Comment by DavidZisky** [comment]
@timoreimann  Yes, I'm trying to marry CCM with K3S ;) I installed K3S standard way (via install script they provide) and I tried basic installation, as well as one with --cloud-provider=externall passed as your docs, suggest (I am also adding --provider-id=digitalocean://[node_id]\ to the nodes)

**Comment by timoreimann** [comment]
@DavidZisky https://rancher.com/docs/k3s/latest/en/networking/#service-load-balancer indicates that there's a built-in load balancer which you may need to disable in order to use others (like the one integrated by CCM). Can you try that?

**Comment by DavidZisky** [comment]
@timoreimann YES! That did the trick :) Many thanks for the help, you're awesome!

**Comment by timoreimann** [comment]
@DavidZisky glad it worked! 🎉
