### ISSUE TITLE
Mixing HTTP, HTTPS and TCP forwarding rules is not supported

### ISSUE THREAD

**Issue by gustavosbarreto** [digitalocean/digitalocean-cloud-controller-manager#316]
Mixing HTTP, HTTPS and TCP forwarding rules is not supported using the cloud controller manager.

According to this:

https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/4d602004386ffe52d627cf6333aa5102c52a21a1/cloud-controller-manager/do/loadbalancers.go#L756

Every entry is created using the default protocol (service.beta.kubernetes.io/do-loadbalancer-protocol):

https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/4d602004386ffe52d627cf6333aa5102c52a21a1/cloud-controller-manager/do/loadbalancers.go#L822

Some enterprise users (me) have complex forwarding rules and need to mix both HTTP, HTTPS and TCP forwarding rules in the same load balancer.

I am hoping that there is a workaround on this without manually changing the forwarding rule protocol in the DO panel.

**Comment by timoreimann** [comment]
hi @gustavosbarreto 

certain rules override the default protocol. For instance, if you specify HTTPS or HTTP/2 ports using the corresponding port annotations, the protocol will be updated accordingly.

There are certain limitations to that though which we plan to fix going forward. Could you outline your exact use case / needs so that we can check if it can be represented with the current set of annotations?

**Comment by gustavosbarreto** [comment]
> hi @gustavosbarreto
> 
> certain rules override the default protocol. For instance, if you specify HTTPS or HTTP/2 ports using the corresponding port annotations, the protocol will be updated accordingly.
> 
> There are certain limitations to that though which we plan to fix going forward. Could you outline your exact use case / needs so that we can check if it can be represented with the current set of annotations?

| EntryProtocol | EntryPort | TargetProtocol | TargetPort         | CertificateID |
|-----------------|-----------|----------------|--------------------|---------------|
| HTTP            | 80        | HTTP           | `-` |               |
| HTTPS           | 443       | HTTP           | `-` | xxxx-xxxx-xxx |
| TCP             | 22        | TCP            | `-` |               |

**Comment by timoreimann** [comment]
Just submitted a PR to support specifying HTTP ports explicitly, which should allow covering your case @gustavosbarreto.

**Comment by gustavosbarreto** [comment]
Hi @timoreimann, thanks! This is exactly what I need.

**Comment by timoreimann** [comment]
Awesome -- change was merged, this will go out with the next CCM / DOKS release happening soon[tm].
