### ISSUE TITLE
Annotation for health check protocol HTTPS

### ISSUE THREAD

**Issue by juburr** [digitalocean/digitalocean-cloud-controller-manager#335]
Annotation `service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol` should support `https` as an option.

HTTPS is already supported through the UI and included in your [documentation](https://www.digitalocean.com/docs/networking/load-balancers/how-to/manage/#health-checks). I'm unable to set it using the annotation though. I have to go to the Digital Ocean website and set it manually.

It's not listed as an option in the [annotation documentation](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/annotations.md#servicebetakubernetesiodo-loadbalancer-healthcheck-protocol), but I tried it anyways and received the following error error message: `Error syncing load balancer: failed to ensure load balancer: failed to build load-balancer request: invalid protocol "https" specified in annotation "service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol"`

**Comment by timoreimann** [comment]
Thanks for reporting @juburr. This should be super easy to support, I submitted a quick PR already.
