### ISSUE TITLE
Help on Custom VPC with DO CCM

### ISSUE THREAD

**Issue by Sandy1438** [digitalocean/digitalocean-cloud-controller-manager#377]
Hi,

I have created a self managed K8s cluster with Custom VPC on DO and have used DO CCM to provision LB service type.

CCM pod is up and running with no issues but when the service type is exposed as LB type the external IP is in pending state.

When I check the events of the service as well as CMM pod I see the below warning:

  Normal   EnsuringLoadBalancer    19s (x17 over 55m)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  18s (x8 over 35m)   service-controller  (combined from similar events): Error syncing load balancer: failed to ensure load balancer: failed to create load-balancer: POST https://api.digitalocean.com/v2/load_balancers: 422 (request "37d3659d-cb45-4da7-b922-57e11777892f") some of the specified target droplets don't belong to the same VPC as the Load Balancer

I could see in the Readme file that when a custom vpc is being used to bootstrap the self managed cluster environment variable DO_CLUSTER_VPC_ID must be specified or Load Balancer creation for services will fail..

Could anyone guide me in which file do we have to specify this env variable?
Is it in CCM pod or in kubelet config files?

Thanks in advance!
BR,
Sandeep.

**Comment by gottwald** [comment]
AFAICS this is needed for the CCM pod.
So going by the manifest examples in this repo you'd need to add it to this env list: https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/ba6aef8dbc3a36a75999f33c368c30551be07c32/docs/example-manifests/cloud-controller-manager.yml#L59

**Comment by Sandy1438** [comment]
Thanks a lot! @gottwald.
I have edited the CMM pod to add the suggested env variable and it works.
