### ISSUE TITLE
udp loadbalancer failing to create

### ISSUE THREAD

**Issue by JamesBrandExpand** [digitalocean/digitalocean-cloud-controller-manager#474]
Per docs https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/#protocol I should be able to create a load balancer with "service.beta.kubernetes.io/do-loadbalancer-protocol: "udp"" annotation. I have the following annotations.

service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: 8081
service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: tcp
service.beta.kubernetes.io/do-loadbalancer-name: staging-vpn-udp
service.beta.kubernetes.io/do-loadbalancer-protocol: udp`

LoadBalancer is never created in DO and k8s shows "Error syncing load balancer: failed to ensure load balancer: failed to build load-balancer request: invalid protocol "udp" specified in annotation "service.beta.kubernetes.io/do-loadbalancer-protocol""

My cluster is on 1.21.11-do.1 per the docs

**Comment by timoreimann** [comment]
Hey @JamesBrandExpand 👋 

your account also needs to be flipped on for UDP usage, which is something that our support team can do. However, that should not produce the error message you've quoted, so I'm a bit perplexed here.

Would you mind filing a support ticket please so that we can take a closer look?

**Comment by kyleishie** [comment]
Hello "another team member here".  To clarify, we did have UDP enabled for all LBs on our account last night.  I can in fact see the UDP option un the DO user interface under forwarding rules.   I would also note that this error was present both before and after UDP was enabled as well as before and after upgrading the cluster to 1.21.11-do.1.

**Comment by timoreimann** [comment]
Thanks for the extra context @kyleishie. I think the error should only show up on cluster versions older than 1.21.11-do.1 where UDP is not enabled in the cluster's backend.

We'll need to take a closer look at your cluster to see what's off. We can do so once you have submitted a support ticket. (Feel free to reference this discussion and drop my name as well for quicker correlation on our end.)

**Comment by timoreimann** [comment]
Oh yeah of course, support is right: for some reason my brain failed to recognize that this is about an unknown annotation, not about an unknown Service configuration field.

Thanks for the update. Looking forward to hearing if it works for you, feel free to close the ticket if it does.

**Comment by timoreimann** [comment]
Glad it works for you now.
