### ISSUE TITLE
Use stringData for Kubernetes Secret containing DO Token. 

### ISSUE THREAD

**Issue by andrewsykim** [digitalocean/digitalocean-cloud-controller-manager#51]
The current examples use `data` in Kubernetes secrets which requires you to base64 encode your secrets. Kuberetes now supports `stringData` which is backwards compatible where the kubelet would end up consuming the data in base64 but we can use string data instead. 

In https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/49, we had a discussion around how we should handle new line characters when we base64 encode the DO token, this would address it. 

More details here https://github.com/kubernetes/kubernetes/issues/19575.

**Comment by bhcleek** [comment]
Sgtm

**Comment by klausenbusk** [comment]
PR opened: https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/58
