### ISSUE TITLE
Does DO CCM allow for Sticky Sessions?

### ISSUE THREAD

**Issue by mklebrasseur** [digitalocean/digitalocean-cloud-controller-manager#61]
Hello,

Does the do ccm allow the ability to configure sticky sessions?

**Comment by andrewsykim** [comment]
Hi @ITPROMatthew! 

You mean sticky sessions on load balancers right?

**Comment by andrewsykim** [comment]
1) Add [annotations](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/do/loadbalancers.go#L35-L58) for sticky sessions
2) Extract sticky session configuration from annotations and add it to the loadbalancer request type [here](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/do/loadbalancers.go#L254-L284). `godo` should already [support sticky sessions](https://github.com/digitalocean/godo/blob/master/load_balancers.go#L127) for LBs.

**Comment by ITPROMatthew** [comment]
Hi @andrewsykim,

Yes exactly for load balancers.

Whats the processes going forward?

**Comment by andrewsykim** [comment]
If you're up for it, you can open a PR for this, or you can wait for one of the maintainers to pick it up.

**Comment by xmudrii** [comment]
I see this is hanging on for some time. Is it available? Can I take it?

**Comment by andrewsykim** [comment]
Yes please @xmudrii :)

**Comment by xmudrii** [comment]
@andrewsykim Started working on it (#64). I believe I'll finish it tomorrow.
