### ISSUE TITLE
Loadbalancer is getting created but no droplets are added.

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [digitalocean/digitalocean-cloud-controller-manager#63]
I have tried this example:https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

And this [one](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/examples/loadbalancers/http-nginx.yml) as well. I just can't seem to make it work. Both of the examples create the load balancers but they add no droplets to the load balancer, and so my service isn't working. 

Is there anything else I need to do? I thought this was an automatic process done by the framework.

**Comment by andrewsykim** [comment]
@IAlwaysBeCoding can you share the logs from the digitalocean cloud controller manager?

**Comment by IAlwaysBeCoding** [comment]
@andrewsykim Excuse my ignorance, but how exactly do you get the logs for the digitalocean cloud controller manager.

I used [typhoon](https://github.com/poseidon/typhoon/tree/master/digital-ocean/container-linux/kubernetes) to launch my first kubernetes cluster.  I followed exactly the same instructions found on the digitalocean cloud controller.

I added `--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname` to the manifest file that typhoon uses to launch the kubernetes cluster. [Here](https://github.com/poseidon/terraform-render-bootkube/blob/master/resources/manifests/kube-apiserver.yaml#L43) is the manifest file where I added  `--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname` .

One thing I noticed is that when I try to get my pods info:
`kubectl get no PRIVATE_IP_DIGITALOCEAN_NODE -o yaml`

I get  the first result like on this [example](https://github.com/digitalocean/digitalocean-cloud-controller-manager/tree/master/examples/nodes). 

Maybe perhaps digitalocean cloud controller isn't running, I'm honestly not sure. I have already tried launching 4 with different manifests modification to see if it works.

I've also successfully ran: `kubectl apply -f releases/secret.yml` and `kubectl apply -f releases/v0.1.3.yml` so I'm still confused as to what else I need to do.

**Comment by andrewsykim** [comment]
You can see if the pod is running by running
```
kubectl -n kube-system get pods
```

you can get the logs from the pod by running
```
kubectl -n kube-system logs <pod-name>
```

**Comment by IAlwaysBeCoding** [comment]
`kubectl -n kube-system get pods`

OUTPUT:

```
NAME                                                    READY     STATUS    RESTARTS   AGE
digitalocean-cloud-controller-manager-957675745-2wnsz   1/1       Running   0          13s
kube-apiserver-l24ft                                    1/1       Running   3          15m
kube-controller-manager-6d7b9454-n6qpd                  1/1       Running   0          15m
kube-controller-manager-6d7b9454-tlknw                  1/1       Running   0          15m
kube-dns-5c47645d88-2f2sv                               3/3       Running   0          15m
kube-flannel-jrmtv                                      2/2       Running   0          15m
kube-flannel-lk4sj                                      2/2       Running   1          15m
kube-flannel-xrvj9                                      2/2       Running   1          15m
kube-proxy-gcm9m                                        1/1       Running   0          15m
kube-proxy-m97xh                                        1/1       Running   0          15m
kube-proxy-rqcdg                                        1/1       Running   0          15m
kube-scheduler-7f9bb9d97f-46dcj                         1/1       Running   0          15m
kube-scheduler-7f9bb9d97f-qsjkz                         1/1       Running   0          15m
pod-checkpointer-lj7wb                                  1/1       Running   0          15m
pod-checkpointer-lj7wb-10.132.90.159                    1/1       Running   0          15m
```


`kubectl -n kube-system logs <pod-name>`

OUTPUT 

```
ERROR: logging before flag.Parse: W0209 21:13:55.653639       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ERROR: logging before flag.Parse: I0209 21:13:55.670060       1 node_controller.go:85] Sending events to api server.
ERROR: logging before flag.Parse: I0209 21:13:55.698766       1 controllermanager.go:239] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: true.
ERROR: logging before flag.Parse: I0209 21:13:55.705921       1 pvlcontroller.go:106] Starting PersistentVolumeLabelController
ERROR: logging before flag.Parse: I0209 21:13:55.705972       1 controller_utils.go:1041] Waiting for caches to sync for persistent volume label controller
ERROR: logging before flag.Parse: I0209 21:13:55.706638       1 service_controller.go:175] Starting service controller
ERROR: logging before flag.Parse: I0209 21:13:55.706676       1 controller_utils.go:1041] Waiting for caches to sync for service controller
ERROR: logging before flag.Parse: I0209 21:13:55.812893       1 controller_utils.go:1048] Caches are synced for service controller
ERROR: logging before flag.Parse: I0209 21:13:55.813201       1 service_controller.go:632] Detected change in list of current cluster nodes. New node set: [10.132.89.77 10.132.90.139]
ERROR: logging before flag.Parse: I0209 21:13:55.813484       1 service_controller.go:640] Successfully updated 0 out of 0 load balancers to direct traffic to the updated set of nodes
ERROR: logging before flag.Parse: I0209 21:13:55.829700       1 controller_utils.go:1048] Caches are synced for persistent volume label controller
```

Thanks, for the help I appreciate it a ton!

**Comment by IAlwaysBeCoding** [comment]
I did a test load balancer using one of the examples provided inside this repository:

`kubectl apply -f https://raw.githubusercontent.com/digitalocean/digitalocean-cloud-controller-manager/master/examples/loadbalancers/http-nginx.yml`

```
kubectl get service http-lb

NAME      TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)        AGE
http-lb   LoadBalancer   10.3.255.230   159.89.243.28   80:30677/TCP   1m

```
As you can see, If I hit the EXTERNAL-IP I get a 503 service unavailable, and inside my DigitalOcean account I see no droplets added to the load balancer. This isn't how is supposed to work right?

**Comment by IAlwaysBeCoding** [comment]
One thing I did manually which made it work, but I know I shouldn't.

1. Delete the Firewall's cluster named after my Kubernetes cluster.
2. Add manually every worker node to the LoadBalancer, and it works with the default nginx app.

However, this is not how kubernetes is supposed to work, since now my droplets worker ips are open to the internet. So there is something that is not being done right on the setup which is not allowing outside traffic, and the digitalocean-controller-manager is not adding the nodes to the loadbalancer.

**Comment by IAlwaysBeCoding** [comment]
Okay, after burning through some more DO credits I've managed to get the droplets added by the load balancer. I needed to rename the droplets to their private ipv4. 

However, the problem still persists of getting 503 on nginx and my droplets health on the loadbalancer show as down. 

Do you know what might be wrong?

**Comment by IAlwaysBeCoding** [comment]
Okay solved it! 

So your instructions aren't really clear at all, and I went and edited all sorts of configuration files for nothing. All, I had to do was use the cluster like I was using it before and change the hostname to the private ip of the droplet, and that's it , it worked!

**Comment by andrewsykim** [comment]
@IAlwaysBeCoding will do some work to try to replicate/fix your issue. What version of Kubernetes were you running?
