### ISSUE TITLE
`k8s.gcr.io` is no longer used

### ISSUE THREAD

**Issue by userbradley** [digitalocean/digitalocean-cloud-controller-manager#665]
Some of the Example manifests reference `k8s.gcr.io` which is frozen and I _think_ will be turned off at some point

https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/

Look at updating the resource's that point to the `k8s.gcr.io` to the new `registry.k8s.io` domain

**Comment by timoreimann** [comment]
Thanks for the note @userbradley.

If I don't get to it, then addressing the problem could be a good first contribution for anyone who wants to pick it up.

**Comment by userbradley** [comment]
@timoreimann here you go: https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/666
