### ISSUE TITLE
LBs does not account for nodes using IPs as node names

### ISSUE THREAD

**Issue by andrewsykim** [digitalocean/digitalocean-cloud-controller-manager#69]
When we add droplets to LBs we only check if the node name matches the droplet names, however, it's common for droplets to be named after their public/private IPs so it should check for that as well. Here's where the check is https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/do/loadbalancers.go#L259.

**Comment by klausenbusk** [comment]
This https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/75 fix the bug, but is add a lot of overhead.. I should redo the PR..

**Comment by andrewsykim** [comment]
Yeah, seems like you can compare the droplet's IP with node.Status.InternalIP

**Comment by klausenbusk** [comment]
Could you take a look again?
