### ISSUE TITLE
Firewall Controller

### ISSUE THREAD

**Issue by andrewsykim** [digitalocean/digitalocean-cloud-controller-manager#86]
DigitalOcean CCM should watch for node events and update firewall rules accordingly. 

related: 
https://github.com/kubernetes/kops/issues/4999 
https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/68

**Comment by Richard87** [comment]
My feeling is that it should open all NodePorts automatically since they are designed to be available from the outside of the cluster?

**Comment by timoreimann** [comment]
@ Richard87 AFAIK, NodePorts on GKE are not publicly exposed by default to enable a distinction between providing local access (within your project / environment) and true public access. Not sure though how that notion maps to DigitalOcean.

**Comment by andrewsykim** [comment]
yeah, so one behaviour of firewall controller would be to turn on access to those node ports if a droplet is added to a LB, etc. This was more desired back when private networking was more like "shared" networking. Today with private netwokring being completely isolated per user perhaps this may not be needed. What do you think?

**Comment by timoreimann** [comment]
Sorry, this one dropped off my radar. Trying to catch up now...

Do all droplets get assigned a publicly routable IP address? If so, wouldn't that make any process running on a Kubernetes cluster and listening on all devices (e.g., a pod with a host port or a native process) be generally accessible from the outside?

That's the only scenario I can see where you may still want to have a firewall to make sure nothing gets accidentally exposed. I suppose users could still manage firewalls on their own, but an integration in DO's CCM might be more convenient?

WDYT?

**Comment by andrewsykim** [comment]
Hmm, good point. For public IPs, I guess firewalls is the only option here. Having DO CCM manage this makes sense to me.

**Comment by andrewsykim** [comment]
Should be easy enough to create a custom controller for this, similar to what we've done for https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/142

**Comment by timoreimann** [comment]
@andrewsykim 👍 a few further design questions come to my mind:

1. should we enable or disable the firewall by default? My guess is we can't just enable it is that would be a breaking change from the existing behavior.
1. how do we allow users to choose a specific default firewall setting (especially the inverse to what we decide for in 1)? Maybe a new CLI parameter to CCM, e.g., `--firewall=off`?
1. how would users toggle the firewall settings for individual ports? I suppose they could go through the usual DO firewall API given that CCM doesn't try to reconcile changes again.

Thanks!

**Comment by andrewsykim** [comment]
1. I think disable by default is a good starting point
2. Flag on CCM is best I think. 
3. I think CCM should reconcile state changes though? I'm not sure if we want to allow users to toggle individual ports. If anything it should be cluster wide setting or at the very least a per Service setting (via annotations). 

^ not strongly held opinions so happy to discuss alternatives.

**Comment by timoreimann** [comment]
@andrewsykim my thinking regarding 3. was that certain users may not want to use a LoadBalancer-typed service for one reason or another (minimizing cost, more sophisticated routing mechanisms, etc.) and instead prefer to talk to NodePorts directly. Not sure how realistic that really is, however, so I'm totally okay with taking the reconciliation route and adjusting only when a use case arises. 👌

**Comment by timoreimann** [comment]
Unless someone wants it more badly than me, I'd take a stab on this one next. :)

**Comment by andrewsykim** [comment]
@timoreimann please go ahead! Just note that we will likely have it disabled by default for quite some time to battle test it and make sure it won't break anyone's production clusters :)

**Comment by timoreimann** [comment]
@andrewsykim makes total sense -- will make sure the default is _off_. 👍

**Comment by timoreimann** [comment]
There's also the open PR #70 which ensures that existing firewalls will be extended / reduced once a LoadBalancer-typed service is created / destroyed. I believe we need to have this as well eventually.

**Comment by timoreimann** [comment]
It took a bit, but we now have #332 open to manage a dedicated firewall for dynamic NodePort access. LBs are not taken into account yet for reasons for scoping and re-questioning the actual need. See https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/68#issuecomment-663959111 for details.
